### PR TITLE
Creating the front-end for the editor

### PR DESCRIPTION
**Pull request by udithishara**
Creating the front-end for the code editor including buttons and navigation bar with minimum css and a proper look

Screenshot of the page below 

image

Related - #5 #2

### CODE REVIEW

**Comment by sirjan13** [comment]
Awesome Work.Merging This

**Comment by udithishara** [comment]
Thank you @sirjan13 🙂

**Comment by sirjan13** [comment]
Can you create an issue for making two separate buttons one for run and other for submit on the bottom left corner of ide

**Comment by udithishara** [comment]
Yeah, sure no problem

**Pull request merged**
