### PR TITLE
added a toogle button to switch

### PR DESCRIPTION
**Pull request by RavinduHasithanjana**
- [ ] I ensure that I have added the Screenshot of the proposed changes.( In case of changes to non .md files)

**Failing this requirement will result in the discardment of the PR**
I added a boostrap toogle button which will allow to change the theme
screen shot 2017-10-05 at 1 41 55 am

### CODE REVIEW

**Comment by Sanskar-Jain** [comment]
@RavinduHasithanjana Also add a screenshot of the toggled state when the theme changes to light.

**Comment by RavinduHasithanjana** [comment]
Sure it is like 
screen shot 2017-10-05 at 2 37 54 am
screen shot 2017-10-05 at 2 38 02 am

**Comment by Sanskar-Jain** [comment]
@RavinduHasithanjana we appreciate your efforts but we wish the text area and the navigation bar  to be also light coloured in case of light theme.

**Comment by RavinduHasithanjana** [comment]
sure i will fix that too

**Comment by RavinduHasithanjana** [comment]
now its right the navbar and the IDE also changes color
screen shot 2017-10-05 at 2 54 29 am
screen shot 2017-10-05 at 2 54 37 am

**Comment by Sanskar-Jain** [comment]
Where are the home and about buttons in light themed ss

**Comment by RavinduHasithanjana** [comment]
okay fixed it
screen shot 2017-10-05 at 3 07 17 am

**Comment by Sanskar-Jain** [comment]
Nice work man🙂

**Comment by RavinduHasithanjana** [comment]
thanks

**Pull request merged**
