### PR TITLE
Fix issue #18, adds CodeMirror, languages, theme, and line numbers

### PR DESCRIPTION
**Pull request by schalkneethling**
- [x] The title of the PR is of the format 'FIX Issue #issue_no'
- [x] I ensure that I have added the Screenshot of the proposed changes.( In case of changes to non .md files)

Adds CodeMirror. 

Here is a screenshot of the editor with HTML with the button set to black:

screen shot 2017-10-05 at 21 26 44

Here is a screenshot of the editor with HTML with the button set to white:

screen shot 2017-10-05 at 21 26 55

### CODE REVIEW

**Comment by sirjan13** [comment]
Great Work

**Comment by sirjan13** [comment]
@schalkneethling Just a small issue when the IDE opens up it just numbers the first line can you fix it so that initially lines uptil the height of the editor are numbered

**Comment by schalkneethling** [comment]
> Just a small issue when the IDE opens up it just numbers the first line can you fix it so that initially lines uptil the height of the editor are numbered

I will have a look whether CodeMirror supports this. To be honest though, that is standard editor behavior though. If look at a new file inside Atom.io for example, only the lines that contains content is numbered. Same thing with Codepen for that matter - https://codepen.io/pen/ (and they also use CodeMirror). So perhaps it is not really a problem?

**Comment by sirjan13** [comment]
Thanks for pointing this out!
Its good to go then no issue

**Comment by schalkneethling** [comment]
@sirjan13  ~ I wonder if the pull request needs to hacktoberfest label?

**Pull request merged**
